apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-singleton-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: www.wuhulala.xyz/middleware/mysql:5.7.22
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-datadir
      volumes:
        - name: mysql-datadir
          hostPath:
            path: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30031
  selector:
    app: mysql