apiVersion: v1
kind: Pod
metadata:
  name: elk
  labels:
    name: elk
spec:
  containers:
    - name: es
      image: www.wuhulala.xyz/docker.elastic.co/elasticsearch/elasticsearch:7.2.0
      resources:
        requests:
          memory: "1Gi"
          cpu: "250m"
        limits:
          memory: "2Gi"
          cpu: "1"
      ports:
        - containerPort: 9200
        - containerPort: 9300
      env:
        - name: "cluster.name"
          value: "docker-cluster"
        - name: "bootstrap.memory_lock"
          value: "true"
        - name: "discovery.type"
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
    - name: kibana
      image: www.wuhulala.xyz/docker.elastic.co/kibana/kibana:7.2.0
      ports:
         - containerPort: 5601
      env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://localhost:9200"
---
apiVersion: v1
kind: Service
metadata:
  name: elk
spec:
  type: NodePort
  ports:
    - port: 9200
      nodePort: 30020
      name: es
    - port: 5601
      nodePort: 30021
      name: kibana
  selector:
    name: elk