version: '2'
services:
    kafka1:
        image:
           registry.cn-hangzhou.aliyuncs.com/wuhulala/kafka:1.1.1
        ports:
           - 9092:9092
        networks:
           - dev_env
        environment:
           - zookeeper_addr=zookeeper:2181
           - broker_id=1
           - kafka_port=9092
    zookeeper:
        image:
            registry.cn-hangzhou.aliyuncs.com/wuhulala/zookeeper:3.4.10
        ports:
           - 2181:2181
        networks:
           - dev_env
    couchbase:
        image:
           couchbase:enterprise-4.6.2
        ports:
           - 8091-8094:8091-8094
           - 11210:11210
        networks:
           - dev_env
    mongodb:
        image:
           registry.cn-hangzhou.aliyuncs.com/wuhulala/mongodb:3.6.4
        ports:
           - 27017:27017
        networks:
           - dev_env
networks:
   dev_env:
    driver: bridge